# Generated by Django 5.1.3 on 2024-11-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_activity_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.skill'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
