# Generated by Django 5.1.3 on 2024-11-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.IntegerField(default=0)),
                ('total_activities', models.IntegerField(default=0)),
            ],
        ),
    ]
